package com.example.domain.utilis

enum class ErrorType {
    GENERAL, UNAUTHORIZED, BLOCKED, NOT_FOUND, SERVER_ERROR, NETWORK, UN_PROCESSABLE,
    TOO_MANY_ATTEMPTS, NOT_VERIFIED_PHONE, NOT_VERIFIED_EMAIL
}